### ISSUE TITLE
back button on list view goes to map view instead

### ISSUE THREAD

**Issue by juliagoolia** [sfbrigade/support-sfusd#225]
if you go to a school profile page from the list view and click back, it takes you to the map view instead of the list view (both mobile and desktop). here's a recording: https://sfbrigade.slack.com/files/U01JYKWN43D/F07KZ01H2EA/rpreplay_final1725567446.mp4

**Comment by thomhickey** [comment]
Hi @juliagoolia ... yes, this will be quite hard to fix as the browser back-button is notoriously hard to manage for single-page-apps like this one. We could, of course, find a way but it will take some effort. What I suggest instead is to give folks a 'back to list' button or some other call to action that will take them back. I think you are using the browser back button because the app doesn't offer ui to take you back. With the ui element it will be much easier to return the user to the list whereas the back button basically does a page-reload on the /map page which is why you see the map instead of the list as map view is the initial state of the map page. Hope that helps explain what's going on here.

**Comment by juliagoolia** [comment]
thanks @thomhickey . I thought relying on browser back-buttons was considered better UX since it's what users expect to be able to work. I'll tag our designers to see what they think, let's discuss Wednesday.

**Comment by thomhickey** [comment]
yes @juliagoolia you're right it's better ux, it's just hard to pull off. just went to peacocktv.com, scrolled down, scrolled right in one of the genres, clicked on a title, then clicked back button and was taken back to somewhere close to where i was, but not exactly. anyway, point is it's notoriously hard to pull off. what we can do is have the click/tap that goes to the list actually create a different route so instead of staying on /map they are taken to /list. then if they click through the list to a school, the back button will bo back to /list. let's talk about it wednesday!

**Comment by thomhickey** [comment]
i sould be more clear ... what's hard is having the back button go back to /map but have the app remember that the state of the /map page had changed to list view. if we're open to using /list or /map#list after changing state to list view, this is not hard.

**Comment by juliagoolia** [comment]
@thomhickey that's what I was thinking too- something like /map#list

**Comment by nickvisut** [comment]
@thomhickey @juliagitis I think it would be great to have a separate route
and I had similar thoughts when first studying the project.

I think that if we can swing it, we could get it to work client-side and
share state or at least prevent having to do extra work when switching (I
noticed that the map reloads entirely each time we switch to it).

I think I have a branch that does a direct DOM manipulation version of this
by using `visibility` instead of toggling on and off via JSX. There’s no
route change, however.

**Comment by thomhickey** [comment]
Great ... happy to jump in and code out /map#list or do you want to do that in your branch @nickvisut ?

**Comment by nickvisut** [comment]
Have at it! And maybe we can compare notes or work together tomorrow/this
week.

I have a personal preference for two fullstack routes /list and /map. And
then we could just rely on browser history for the back button to work, as
you were suggesting.

CC @BeeSeeWhy for thoughts
